name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3

      # Build + tests normales
      - name: Build
        run: ./gradlew build --no-daemon

      # Check de API estable
      - name: API Check
        run: ./gradlew :coreengine-api:apiCheck --no-daemon
